Create Recipe for using multiple BackendConfigs for multiple ports on istio
GoogleCloudPlatform/gke-networking-recipes pull request #102
Opened 2022-07-15 18:02 UTC by gleichda

Fixes #24

2022-08-04 14:19 UTC, felixskaiser commented on ingress/single-cluster/ingress-asm-multi-backendconfig/README.md
> +
One could also go into the other advantages of this approach, apart from being able to "only" use multiple BackendConfigs with an IG. For example:

```suggestion
Replacing the default Kubernetes `LoadBalancer` service with an Ingress resource to get traffic to an Istio Ingress Gateway generally allows you to combine the features of Istio Ingress Gateways resource with the features of a [External HTTP(S) load balancer](https://cloud.google.com/load-balancing/docs/https) and [GKE ingress](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features): besides Backend Configs, this also allows for example to use global load balancing or FrontendConfigs (such as for HTTP-to-HTTPS redirect).

```

2022-08-04 14:23 UTC, felixskaiser commented on ingress/single-cluster/ingress-asm-multi-backendconfig/README.md
> +            * Port 15021 is used for the ingressgatweay health ckeck and maps to the target port 15021.
```suggestion
            * Port 15021 is used for the ingressgatweay health check and maps to the target port 15021.
```

2022-08-04 14:47 UTC, felixskaiser commented on ingress/single-cluster/ingress-asm-multi-backendconfig/README.md
> +            * In contrast to that port 15022 (`http2`) and 15023 (`custom-backendconfig-port`) are both mapped to port 80 of the `istio-ingressgateway` which serves the normal user-facing traffic. \
Change markdown formatting for better legibility
```suggestion
        * In contrast to that, port 15022 (`http2`) and 15023 (`custom-backendconfig-port`) are both mapped to port 80 of the `istio-ingressgateway` which serves the normal user-facing traffic.

```

2022-08-04 14:47 UTC, felixskaiser commented on ingress/single-cluster/ingress-asm-multi-backendconfig/README.md
> +            While both ports (15022 und 15023) basically serve the same traffic now the annotation `cloud.google.com/backend-config: '{"ports": {"http2":""ingressgateway-default","custom-backendconfi
Change markdown formatting for better legibility, add a note about the extensibility of this approach
```suggestion
        While both ports (15022 und 15023) basically serve the same traffic now the annotation `cloud.google.com/backend-config: '{"ports": {"http2":""ingressgateway-default","custom-backendconfig-port":"custom-backendconfig"}}'` tells the GKE Ingress controller to apply the `ingressgateway-default`to port 15022(`http2`) and BackendConfig `custom-backendconfig` to port 15023(`custom-backendconfig-port`).
      > **Note**
      > The number of combinations of additional ports and BackendConfigs is arbitrarily extensible
```

2022-08-04 14:49 UTC, felixskaiser approved these changes
I enjoyed discussing this with you in the past @gleichda, and I'm happy that this approach gets to be shared publicly :+1:

2022-08-04 15:03 UTC, danielmarzini requested changes
Hey @gleichda, awesome work, thank you! Could you please add, in addition, a single recipe file?

2022-08-08 10:02 UTC, danielmarzini approved these changes

2022-08-08 10:04 UTC, danielmarzini commented
Hey @gleichda, as we saw it together, I'm approving this, please just add on the REAME the explanation on why this one is splitted in two files. Thanks!

2022-08-08 10:05 UTC, danielmarzini commented
Hey @felixskaiser thanks for you contribution. Please, take a look to the CLA procedure in order to let us accept it, thanks! You can have a check, also, here: https://github.com/GoogleCloudPlatform/gke-networking-recipes/pull/102/checks?check_run_id=7723189581

2022-08-08 11:09 UTC, danielmarzini commented
@boredabdel this one can be merged.

2022-08-25 11:41 UTC, danielmarzini commented
@boredabdel kindly ping ;)

2022-08-25 11:44 UTC, boredabdel commented
Sorry i missed this one. on it

2022-08-25 11:44 UTC, merged